"""
Integration tests for the full encode-decode pipeline.
"""

import pytest

from core.database import open_memory_db
from core.pipeline import run_pipeline
from core.decoder import full_decode


# Sample GCode with a few simple layers
SIMPLE_GCODE = """
; Generated by Cura
G28
G29
M104 S200

; Layer 0, Z = 0.20
G0 Z0.20
G1 X10 Y10 E0
G1 X20 Y10 E1 F600
G1 X20 Y20 E2 F600
G1 X10 Y20 E3 F600
G1 X10 Y10 E4 F600
; Infill for layer 0
G1 X12 Y12 E5 F1000
G1 X18 Y12 E6 F1000
G1 X12 Y18 E7 F1000
G1 X18 Y18 E8 F1000
G1 X15 Y15 E9 F1000
G1 X12 Y15 E10 F1000
G1 X18 Y15 E11 F1000

; Layer 1, Z = 0.40
G0 Z0.40
G1 X10 Y10 E12
G1 X20 Y10 E13 F600
G1 X20 Y20 E14 F600
G1 X10 Y20 E15 F600
; Infill for layer 1
G1 X12 Y12 E16 F1000
G1 X18 Y12 E17 F1000
G1 X12 Y18 E18 F1000
G1 X18 Y18 E19 F1000
G1 X15 Y15 E20 F1000
G1 X12 Y15 E21 F1000
G1 X18 Y15 E22 F1000
G1 X14 Y14 E23 F1000
G1 X14 Y16 E24 F1000
G1 X16 Y14 E25 F1000
G1 X16 Y16 E26 F1000
G1 X13 Y15 E27 F1000
G1 X17 Y15 E28 F1000

M104 S0
"""


def test_encode_pipeline_creates_database():
    """Test that encoding pipeline creates database records."""
    conn = open_memory_db()
    
    result = run_pipeline(SIMPLE_GCODE, "test.gcode", conn)
    
    # Verify result metadata
    assert result.total_layers > 0
    assert result.file_id is not None
    assert result.nominal_spacing_mm > 0
    
    # Verify database has file record
    file_row = conn.execute(
        "SELECT * FROM files WHERE file_id = ?", (result.file_id,)
    ).fetchone()
    assert file_row is not None
    assert file_row["filename"] == "test.gcode"

    conn.close()


def test_encode_pipeline_creates_layer_records():
    """Test that layers are recorded in database."""
    conn = open_memory_db()
    
    result = run_pipeline(SIMPLE_GCODE, "test.gcode", conn)
    
    # Verify layer records exist
    layer_rows = conn.execute(
        "SELECT * FROM layers WHERE file_id = ? ORDER BY layer_idx",
        (result.file_id,),
    ).fetchall()
    
    assert len(layer_rows) > 0
    
    # Check that layers have expected fields
    for row in layer_rows:
        assert row["layer_idx"] is not None
        assert row["z_height_mm"] is not None
        assert row["line_count"] >= 0
        assert row["encoded"] in (0, 1)

    conn.close()


def test_encode_produces_modified_gcode():
    """Test that encoding produces modified GCode."""
    conn = open_memory_db()
    
    result = run_pipeline(SIMPLE_GCODE, "test.gcode", conn)
    
    # Modified GCode should contain original plus modifications
    assert len(result.modified_gcode) > 0
    assert "Layer 0" in result.modified_gcode  # Original comment should be there
    
    conn.close()


def test_encode_preserves_original_content():
    """Test that encoding preserves essential GCode structure."""
    conn = open_memory_db()
    
    result = run_pipeline(SIMPLE_GCODE, "test.gcode", conn)
    
    # Should preserve key G-codes
    assert "G28" in result.modified_gcode
    assert "G29" in result.modified_gcode
    assert "G0 Z" in result.modified_gcode or "G0 Z0" in result.modified_gcode
    
    conn.close()


def test_encode_with_override_nominal_spacing():
    """Test encoding with manually specified nominal spacing."""
    conn = open_memory_db()
    
    result = run_pipeline(
        SIMPLE_GCODE,
        "test.gcode",
        conn,
        nominal_spacing_override=0.5,  # Override with 0.5mm
    )
    
    assert result.nominal_spacing_mm == 0.5
    
    conn.close()


def test_multiple_files_dont_collide():
    """Test that different GCode files get different file_ids."""
    conn = open_memory_db()
    
    result1 = run_pipeline(SIMPLE_GCODE, "test1.gcode", conn)
    
    # Create slightly different GCode
    gcode2 = SIMPLE_GCODE.replace("X10", "X11")
    result2 = run_pipeline(gcode2, "test2.gcode", conn)
    
    # Should have different file_ids
    assert result1.file_id != result2.file_id
    
    conn.close()


def test_same_gcode_twice_returns_same_file_id():
    """Test that encoding the same GCode twice returns same file_id."""
    conn = open_memory_db()
    
    result1 = run_pipeline(SIMPLE_GCODE, "test.gcode", conn)
    result2 = run_pipeline(SIMPLE_GCODE, "test.gcode", conn)
    
    # Same SHA256 should return same file_id
    assert result1.file_id == result2.file_id
    
    conn.close()


def test_pipeline_result_fields():
    """Test that pipeline result has all expected fields."""
    conn = open_memory_db()
    
    result = run_pipeline(SIMPLE_GCODE, "test.gcode", conn)
    
    assert hasattr(result, "modified_gcode")
    assert hasattr(result, "file_id")
    assert hasattr(result, "total_layers")
    assert hasattr(result, "encoded_count")
    assert hasattr(result, "skipped_count")
    assert hasattr(result, "nominal_spacing_mm")
    assert hasattr(result, "layer_records")
    
    # Verify counts are consistent
    assert result.total_layers == result.encoded_count + result.skipped_count
    
    conn.close()


def test_encode_decode_integration():
    """Test full encode-decode cycle (requires mock vision data)."""
    # This test verifies the database structure is correct for decoding
    # Full vision integration requires mocking the vision module
    conn = open_memory_db()
    
    result = run_pipeline(SIMPLE_GCODE, "test.gcode", conn)
    
    # Verify encoded layers exist
    encoded_layers = conn.execute(
        "SELECT * FROM layers WHERE file_id = ? AND encoded = 1",
        (result.file_id,),
    ).fetchall()
    
    assert len(encoded_layers) > 0
    
    # Each encoded layer should have payload data
    for layer in encoded_layers:
        assert layer["payload_bits"] is not None
        assert layer["correlated_payload"] is not None
    
    conn.close()
